//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonitorBlind.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonitorBlind.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Press the key you want to set as the shortcut. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string KeySettingDialogLabel_01 {
            get {
                return ResourceManager.GetString("KeySettingDialogLabel_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLabel_02 {
            get {
                return ResourceManager.GetString("MenuLabel_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLabel_03 {
            get {
                return ResourceManager.GetString("MenuLabel_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duplicate(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuLabel_04 {
            get {
                return ResourceManager.GetString("MenuLabel_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Opacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_04 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_06 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables shortcut key to switch show/hide blinds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_09 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select Key に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_10 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Current Key Setting : に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_11 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enables to move or zoom in/out blinds. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowLabel_12 {
            get {
                return ResourceManager.GetString("SettingWindowLabel_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SettingWindowTitle {
            get {
                return ResourceManager.GetString("SettingWindowTitle", resourceCulture);
            }
        }
    }
}
